// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: trial.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Trial {
  public static partial class Trial
  {
    static readonly string __ServiceName = "trial.Trial";

    static readonly grpc::Marshaller<global::Trial.HelloRequest> __Marshaller_trial_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Trial.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Trial.HelloReply> __Marshaller_trial_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Trial.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Trial.HelloRequest, global::Trial.HelloReply> __Method_MessageExamples = new grpc::Method<global::Trial.HelloRequest, global::Trial.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MessageExamples",
        __Marshaller_trial_HelloRequest,
        __Marshaller_trial_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Trial.TrialReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Trial</summary>
    public abstract partial class TrialBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Trial.HelloReply> MessageExamples(global::Trial.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Trial</summary>
    public partial class TrialClient : grpc::ClientBase<TrialClient>
    {
      /// <summary>Creates a new client for Trial</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TrialClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Trial that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TrialClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TrialClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TrialClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Trial.HelloReply MessageExamples(global::Trial.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageExamples(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Trial.HelloReply MessageExamples(global::Trial.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MessageExamples, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Trial.HelloReply> MessageExamplesAsync(global::Trial.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageExamplesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Trial.HelloReply> MessageExamplesAsync(global::Trial.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MessageExamples, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TrialClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TrialClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TrialBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_MessageExamples, serviceImpl.MessageExamples).Build();
    }

  }
}
#endregion
